services:
  frontend:
    build: ./frontend  # <-- make sure this matches the real folder name
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"